'pkg: opencli':
  - '### Which (website|package|website or package) is this (bug report|feature
    request) for\?\n\nopencli\n'
'pkg: scripts':
  - '### Which (website|package|website or package) is this (bug report|feature
    request) for\?\n\nscripts\n'
website:
  - '### Which (website|package|website or package) is this (bug report|feature
    request) for\?\n\nwebsite\n'
website:docs:
  - '### Which (website|package|website or package) is this (bug report|feature
    request) for\?\n\ndocs\n'
