- name: actions
  description: Modify GitHub Actions workflows
  color: f5c9ff
- name: dependencies
  description: Pull requests that update a dependency file
  color: e0e3ff
- name: 'good first issue'
  description: Good first issue for newcomers
  color: c8ffef
- name: packages:opencli
  description: Modify the opencli package
  color: 5865f2
- name: packages:scripts
  description: Modify the scripts package
  color: 5865f2
- name: website
  description: Modify the landing page of the project
  color: 35ed7e
- name: website:docs
  description: Modify the documentation of the project
  color: 35ed7e
