'actions':
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
'pkg: opencli':
  - changed-files:
      - any-glob-to-any-file:
          - packages/opencli/*
          - packages/opencli/**/*
'pkg: scripts':
  - changed-files:
      - any-glob-to-any-file:
          - scripts/*
          - scripts/**/*
'website':
  - changed-files:
      - any-glob-to-any-file:
          - website/*
          - website/**/*
