- name: actions
  description: Modify GitHub Actions workflows
<<<<<<< HEAD
  color: f5c9ff
=======
  color: e99695
>>>>>>> a51600606a4c9c5cb08b8d3a4cc6938f79046cfc
- name: dependencies
  description: Pull requests that update a dependency file
  color: e0e3ff
- name: packages:opencli
  description: Modify the opencli package
  color: 5865f2
- name: packages:scripts
  description: Modify the scripts package
  color: 5865f2
- name: website
  description: Modify the landing page of the project
  color: 35ed7e
- name: website:docs
  description: Modify the documentation of the project
  color: 35ed7e
