packages:
  - 'templates/**/*'
  - 'packages/**/*'
  - 'scripts'
  - 'website'
  # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - '!**/.vercel/**'

allowBuilds:
  esbuild: true
  unrs-resolver: false

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

patchedDependencies:
  '@changesets/get-github-info@0.7.0': patches/@changesets__get-github-info@0.7.0.patch

peerDependencyRules:
  allowAny:
    - '*'
  ignoreMissing:
    - '*'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
