name: 'Upload Coverage'
description: 'Uploads code coverage reports to codecov with separate flags for separate packages'

inputs:
  codecov_token:
    description: 'Codecov token.'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Upload OpenCLI Coverage
      if: ${{ hashFiles('packages/opencli/coverage/cobertura-coverage.xml') != '' }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
      with:
        files: ./packages/opencli/coverage/cobertura-coverage.xml
        disable_search: true
        flags: opencli
        token: ${{ inputs.CODECOV_TOKEN }}
