name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/**'

permissions: {}

# Automatically cancel older in-progress jobs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  FORCE_COLOR: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # Required by dorny/paths-filter to read changed files
    outputs:
      opencli-types: ${{ steps.filter.outputs.opencli-types }}
      ci: ${{ steps.filter.outputs.ci }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          filters: |
            opencli-types:
              - 'packages/opencli/types/**'
            ci:
              - '.github/workflows/ci.yml'

  build:
    name: 'Build: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    permissions:
      contents: read # Checkout only
    strategy:
      matrix:
        # windows-latest is still windows-2022 for some reason, even though the windows-2025 image is GA
        OS: [ubuntu-latest, windows-2025]
        NODE_VERSION: [22]
      fail-fast: true
    steps:
      # Disable crlf so all OS can share the same Turbo cache
      # https://github.com/actions/checkout/issues/135
      - name: Disable git crlf
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Setup node@${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.NODE_VERSION }}
          package-manager-cache: false

      # Only build in ubuntu as windows can share the build cache.
      # Also only build in core repo as forks don't have access to the Turbo cache.
      - name: Build Packages
        if: ${{ matrix.os == 'ubuntu-latest' && github.repository_owner == 'hadez8877' }}
        run: pnpm run build

  linters:
    name: Linters
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read # Checkout only
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.15.0
          package-manager-cache: false

      - name: Build Packages
        run: pnpm exec turbo run build --filter="...[HEAD^1]" --concurrency=4

      - name: Linters (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm exec turbo run lint --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]" --concurrency=4 -- --format=compact

      - name: Linters (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm exec turbo run lint --filter="...[HEAD^1]" --concurrency=4 -- --format=compact

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    permissions:
      contents: read # Checkout only
    needs: build
    strategy:
      matrix:
        OS: [ubuntu-latest, macos-14, windows-2025]
        NODE_VERSION: [22, 24]
        # We only test Node 22 on macOS and Windows to reduce CI usage.
        # This exclude config tells GitHub to skip the items in the matrix that run on macOS or
        # Windows and use one of the older Node versions.
        exclude:
          - os: macos-14
            NODE_VERSION: 22
          - os: windows-2025
            NODE_VERSION: 22
      fail-fast: false
    env:
      NODE_VERSION: ${{ matrix.NODE_VERSION }}
    steps:
      - name: Disable git crlf
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.15.0
          package-manager-cache: false

      - name: Tests (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm exec turbo run test --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]" --concurrency=4

      - name: Tests (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm exec turbo run test --filter="...[HEAD^1]" --concurrency=4

  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ github.repository_owner == 'hadez8877' }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Upload Coverage
        uses: ./.github/actions/upload-coverage
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
