name: Semgrep OSS scan

permissions: {}

on:
  pull_request: {}
  schedule:
    - cron: '0 0 * * 6'
jobs:
  semgrep:
    name: semgrep-oss
    runs-on: ubuntu-latest
    permissions:
      contents: read # Checkout only
    container:
      image: semgrep/semgrep@sha256:bc8b15e245d7bd392bcadce7ef4db36601b375fab35bfd8070ed8ae3d7824c74 # v1.157.0
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: semgrep scan --config=auto
