name: Semgrep OSS scan

permissions: {}

on:
  pull_request: {}
  schedule:
    - cron: '0 0 * * 6'
jobs:
  semgrep:
    name: semgrep-oss
    runs-on: ubuntu-latest
    permissions:
      contents: read # Checkout only
    container:
      image: semgrep/semgrep@sha256:525beaba156b9bd3f9847d6ec0eb8f308e11f407e0c0b2da641e7c8dd99c97d6 # v1.157.0
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - run: semgrep scan --config=auto
