name: Semgrep OSS scan

permissions: {}

on:
  pull_request: {}
  schedule:
    - cron: '0 0 * * 6'
jobs:
  semgrep:
    name: semgrep-oss
    runs-on: ubuntu-latest
    permissions:
      contents: read # Checkout only
    container:
      image: semgrep/semgrep@sha256:bd2ada83c7aa5a60e07d86ee84ba0c12282264781c8d783be5a912549a94394f # v1.157.0
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: semgrep scan --config=auto
